---
title: "vol.02 Rolling window analysis"
output: html_notebook
---

1. Data sorting
```{r}
library(openintro) # please check whether you have installed this package; otherwise please install first

data(smoking)
dt = smoking[order(smoking$age),]
dt = dt[!is.na(dt$amt_weekdays), ]

plot(dt$amt_weekdays ~ dt$age)

```

2. Setting parameters
```{r}
step.age = 0.1
window.age = 10

min.age = min(dt$age)
max.age = max(dt$age)

wm.df =  data.frame(wm.age = numeric(0), wm.amt_wk = numeric(0))

```

3. Writing a loop
```{r}
i = 0
n_step = (max.age - min.age - window.age)/step.age

for (i in 0:n_step)  {
  filter.age = dt$age >= (min.age + i*step.age) & 
    dt$age <= (min.age + i*step.age + window.age)
  sub.dt = dt[filter.age, ]
  wm.age = mean(sub.dt$age)
  wm.amt_wk = mean(sub.dt$amt_weekdays)
  wm.dt = list(wm.age, wm.amt_wk)
  wm.df = rbind(wm.df, wm.dt)
  i + 1}

colnames(wm.df) = c('m.age', 'm.amt_wk')

```

4. Plotting
```{r}
# setting up filters for gender
filter_f = dt$gender == 'Female'
filter_m = dt$gender == 'Male'

dt$color = as.character(dt$gender)
dt$color[dt$color == 'Female'] = 'pink'
dt$color[dt$color == 'Male'] = 'light blue'

# plotting
plot(dt$age[filter_m], dt$amt_weekdays[filter_m],
     xlim = c(15, 95), ylim = c(0, 55),
     xaxt="none", yaxt="none", xlab="",ylab="",
     pch = 16, col = alpha(unique(dt$color[filter_m]), 0.5), tcl=0.3)
points(dt$age[filter_f], dt$amt_weekdays[filter_f],
       pch = 16, col = alpha(unique(dt$color[filter_f]), 0.5))
points(wm.df$m.age, wm.df$m.amt_wk, pch = 21, bg = '#FF0033', cex = 2.5)
axis(1, seq(15, 95, 5), las = 1, font = 2,cex.axis = 1)
axis(2, seq(0, 55, 5), las = 2, font = 2)
mtext(side=1, line=2, "Age", font=2,cex=1.2)
mtext(side=2, line=2, "Number of cigarettes/day", font=2, cex=1.2)
mtext(side=3, line=1, "Age dependence of smoking amounts", col="blue", font=3, cex=1.5)
abline(v = c(62.5, 82.5), lwd=1.2, lty=2)
legend('topleft', legend=c('Female', 'Male', 'Summarized data'), pch = 16,
       col = c('pink', 'lightblue', 'red'), cex=1.0)
```

